### ISSUE TITLE
Download Manifest is working - Download Package / App fails

### ISSUE THREAD

**Issue by pri-kise** [365businessdev/alget#7]
I've got a problem with the download of the symobls from an AppSource App.

The manifest can be downloaded:
```
INFO] Downloading package manifest PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.59292 from AppSourceSymbols feed
```

And then the download fails:
```
INFO] Downloading package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.0.0 from AppSourceSymbols feed
Z [ERROR] Failed to download package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) from AppSourceSymbols feed
```

When I check the developer tools, then I can see a 404.
> workbench.desktop.main.js:sourcemap:613 [Extension Host] Error downloading package: AxiosError: Request failed with status code 404
	at Ze (c:\Users\xxx\.vscode\extensions\365businessdevelopment.365businessdev-alget-0.0.3\dist\extension.js:2:308134)
	at IncomingMessage.<anonymous> (c:\Users\xxx\.vscode\extensions\365businessdevelopment.365businessdev-alget-0.0.3\dist\extension.js:2:320227)
	at IncomingMessage.emit (node:events:531:35)
	at endReadableNT (node:internal/streams/readable:1696:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
	at an.request (c:\Users\xxx\.vscode\extensions\365businessdevelopment.365businessdev-alget-0.0.3\dist\extension.js:2:332736)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.downloadPackage (c:\Users\xxx\.vscode\extensions\365businessdevelopment.365businessdev-alget-0.0.3\dist\extension.js:2:182638)
	at async t.default.install (c:\Users\xxx\.vscode\extensions\365businessdevelopment.365businessdev-alget-0.0.3\dist\extension.js:2:195963)

**Comment by sirhc101** [comment]
I tried myself, but cannot reproduce it 🧐

```log
2024-11-05T13:56:18.589Z [INFO] Searching matching version for package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) in version range 2.1.59292
2024-11-05T13:56:18.589Z [INFO] Checking dependencies for package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.59292
2024-11-05T13:56:18.590Z [INFO] Downloading package manifest PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.59292 from AppSourceSymbols feed
2024-11-05T13:56:18.732Z [INFO] Fetching dependencies for package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.59292
[...]
2024-11-05T13:56:22.155Z [INFO] Downloading dependency prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6 version 1.0.0
2024-11-05T13:56:22.155Z [INFO] Loading packages from feeds
2024-11-05T13:56:22.155Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:22.846Z [INFO] 0 packages received from feed
2024-11-05T13:56:22.846Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/AppSourceSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:25.456Z [INFO] 1 packages received from feed
2024-11-05T13:56:25.456Z [INFO] Searching matching version for package PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) in version range 1.0.0
2024-11-05T13:56:25.456Z [INFO] Checking dependencies for package PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) version 1.0.52763
2024-11-05T13:56:25.457Z [INFO] Downloading package manifest PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) version 1.0.52763 from AppSourceSymbols feed
2024-11-05T13:56:25.616Z [INFO] Fetching dependencies for package PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) version 1.0.52763
2024-11-05T13:56:25.616Z [INFO] Downloading dependency Microsoft.Application.W1.symbols version 23.0.0
2024-11-05T13:56:25.616Z [INFO] Loading packages from feeds
2024-11-05T13:56:25.616Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:26.068Z [INFO] 0 packages received from feed
2024-11-05T13:56:26.068Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/AppSourceSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:26.363Z [INFO] 0 packages received from feed
2024-11-05T13:56:26.363Z [ERROR] Package Microsoft.Application.W1.symbols not found
2024-11-05T13:56:26.363Z [INFO] Downloading package PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) version 1.0.52763 from AppSourceSymbols feed
2024-11-05T13:56:26.923Z [INFO] Downloaded package PI Html Editor (ID: prismainformatikGmbH.PIHtmlEditor.symbols.bd009988-0251-416f-8c28-e581719632d6) from AppSourceSymbols feed
2024-11-05T13:56:26.930Z [INFO] PI Html Editor downloaded to '/Users/christophkrieg/Code/DevOps/AL/app/.alpackages/prisma informatik GmbH_PI Html Editor_1.0.52763.app'
2024-11-05T13:56:26.933Z [INFO] Downloading dependency prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325 version 1.1.0
2024-11-05T13:56:26.933Z [INFO] Loading packages from feeds
2024-11-05T13:56:26.933Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:27.641Z [INFO] 0 packages received from feed
2024-11-05T13:56:27.641Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/AppSourceSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:27.921Z [INFO] 1 packages received from feed
2024-11-05T13:56:27.922Z [INFO] Searching matching version for package prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) in version range 1.1.0
2024-11-05T13:56:27.922Z [INFO] Checking dependencies for package prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) version 1.1.57266
2024-11-05T13:56:27.923Z [INFO] Downloading package manifest prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) version 1.1.57266 from AppSourceSymbols feed
2024-11-05T13:56:28.161Z [INFO] Fetching dependencies for package prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) version 1.1.57266
2024-11-05T13:56:28.161Z [INFO] Downloading dependency Microsoft.Application.W1.symbols version 21.0.0
2024-11-05T13:56:28.161Z [INFO] Loading packages from feeds
2024-11-05T13:56:28.161Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/MSSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:28.608Z [INFO] 0 packages received from feed
2024-11-05T13:56:28.608Z [INFO] Fetching packages from 'https://dynamicssmb2.pkgs.visualstudio.com/DynamicsBCPublicFeeds/_packaging/AppSourceSymbols/nuget/v3/index.json' feed url
2024-11-05T13:56:28.898Z [INFO] 0 packages received from feed
2024-11-05T13:56:28.899Z [ERROR] Package Microsoft.Application.W1.symbols not found
2024-11-05T13:56:28.900Z [INFO] Downloading package prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) version 1.1.57266 from AppSourceSymbols feed
2024-11-05T13:56:29.426Z [INFO] Downloaded package prisma License Module (ID: prismainformatikGmbH.prismaLicenseModule.symbols.42d8c02a-2ad8-482b-938c-6bad0bfd9325) from AppSourceSymbols feed
2024-11-05T13:56:29.428Z [INFO] prisma License Module downloaded to '/Users/christophkrieg/Code/DevOps/AL/app/.alpackages/prisma informatik GmbH_prisma License Module_1.1.57266.app'
2024-11-05T13:56:29.428Z [INFO] Downloading package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) version 2.1.59292 from AppSourceSymbols feed
2024-11-05T13:56:30.631Z [INFO] Downloaded package PI Conteksto (ID: prismainformatikGmbH.PIConteksto.symbols.a649877a-80de-42ce-b0ae-4dcce4a4f770) from AppSourceSymbols feed
2024-11-05T13:56:30.637Z [INFO] PI Conteksto downloaded to '/Users/christophkrieg/Code/DevOps/AL/app/.alpackages/prisma informatik GmbH_PI Conteksto_2.1.59292.app'
```

I will add some additional logging in the next version.
